### ISSUE TITLE
Add `no-unsupported-features`

### ISSUE THREAD

**Issue by jamestalmage** [xojs/xo#108]
https://github.com/mysticatea/eslint-plugin-node/blob/master/docs%2Frules%2Fno-unsupported-features.md

I think it would need to be opt-in, but it might be worth the addition of an extra config option in `xo`.

``` js
{
  xo: {
    noUnsupported: true // or "0.10" - true pulls from engines
  }
}
```

It would be nice to automatically disable the rule for AVA tests.

**Comment by sindresorhus** [comment]
See https://twitter.com/sindresorhus/status/722336552395755524 and https://github.com/mysticatea/eslint-plugin-node/issues/29.

**Comment by jfmengels** [comment]
I would definitely like to have this available, but using it with AVA is going to be hard.
Maybe once https://github.com/eslint/eslint/issues/3611 gets implemented, this will make it easier?

**Comment by sindresorhus** [comment]
@jfmengels XO already supports glob targeted config. See the readme ;)

**Comment by jfmengels** [comment]
Ah, true. Keep forgetting that :D

**Comment by sindresorhus** [comment]
Relevant: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-deprecated.md

**Comment by pvdlg** [comment]
That could be enabled now that we support the [`nodeVersion` option](https://github.com/xojs/xo#nodeversion). So one can define different Node target versions for different files (sources and transpiled for example).

However the rule `no-unsupported-features` accept only a version number in it's [version option](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md#version) while our [`nodeVersion` option](https://github.com/xojs/xo#nodeversion) accepts a version or a range similarly to`engines.node` in `package.json`.
So when https://github.com/mysticatea/eslint-plugin-node/issues/119 is resolved the rule could be enabled.
