### ISSUE TITLE
Classifications config

### ISSUE THREAD

**Issue by jamestalmage** [xojs/xo#127]
I like the 300 length limit for source files, but it would be better if it didn't apply to tests.

**Comment by sindresorhus** [comment]
@jamestalmage Agreed, but how would we do that? Should we just add some custom logic for AVA?

**Comment by jamestalmage** [comment]
Sure, we could make that the default.

I am almost wondering if we couldn't build an alternative to the `overrides` array that allowed classifications:

```json
{
  "xo": {
    "classifications": {
      "tests": ["test/**", "!test/fixtures/**"]
    },
    "classificationOverlays": {
      "tests": {
       "rules": {
          ...
        }
      }
    }
  }
}
```

-- 

It almost seems like `classifications` could be generalized into it's own reusable module:

- `tests` vs `sources` vs `helpers` for AVA
- `covered` vs `uncovered` for NYC
- Specific linter rules per classification for eslint / xo
- Specific transforms per classification for babel / browserify

Globs are great for selecting files, but they lack metada about what type of file they are selecting, so I end up repeating similar globs multiple times in the codebase / config.

**Comment by sindresorhus** [comment]
Seems a bit overcomplicated.

**Comment by jamestalmage** [comment]
I agree, but I think we could build in default actions based on classification. Users wouldn't necessarily have to write the `classificationOverlays` section themselves.

We just tell them, anything given the `test` classification will have these extra set of linter rules applied.

**Comment by Qix-** [comment]
Seems rather arbitrary  and complicated. All we're trying to is to exclude a few files from a single rule.

**Comment by jamestalmage** [comment]
>  All we are trying to is to exclude a few files from a single rule.

Yeah, I get that, but I'm thinking further down the road. 

For example, in addition to this, I often want to enable `esnext` for my tests when using AVA, so I use overrides like this:

```js
"xo": {
    "overrides": [
      {
        "files": ["test/**/*.js"],
        "esnext": true,
        "rules": {
          "max-lines": 0
        }
      }
    ]
}
```

I think if would be cool if we provided a mechanism like this that did the same thing:

```js
"xo": {
  "classifications": {
    "avatest": ["test/**/*.js"], // esnext and ava plugin enabled, max-lines disabled
    // or
    "tests": ["test/**/*.js"] // only disables max-lines,
    // maybe
    "mocha": [...] // enable the mocha env (and maybe mocha specific rules?)
    "browser": [...] // enable the browser env (and maybe browser specific rules?)
  }
}
```

Now maybe I am getting ahead of myself, and "is this a test or not" is the only type of classification we care about, so we could just do this:

```js
"xo": {
  "esnext": "tests",  // enables esnext for tests
  "tests": ["test/**/*.js"]
}
```

Still, I think the idea of building a way to classify files other interesting implications. What if it was top level, and shared by other tools:

```js
"classifications": {
  "tests": ["test/**/*.js"] 
}
```

NYC could use the `test` classification to ignore for coverage, XO can use it to adjust linting, Babel could allow you to adjust transpilation based on classification

**Comment by sindresorhus** [comment]
I would have liked to simplify all this too, but I don't the classification thing is going to work out.
