### ISSUE TITLE
Expects 5 indentations instead of 4 since recently

### ISSUE THREAD

**Issue by SamVerschueren** [xojs/xo#197]
I came across this in `np` as of today, not sure why it never failed earlier.

Apparently, `XO` expects 4 indentations instead of 5 in [this](https://github.com/sindresorhus/np/blob/master/lib/prerequisite.js#L47-L58) code block. Right [here](https://github.com/sindresorhus/np/blob/master/lib/prerequisite.js#L47) and [here](https://github.com/sindresorhus/np/blob/master/lib/prerequisite.js#L52). I'm not sure if `XO` can actually do something about that as it looks like it's an ESLint rule.

Sorry for the quick explanation but don't have much time now to look into it.

**Comment by sindresorhus** [comment]
Seems like it's because of https://github.com/eslint/eslint/issues/7320.

I've disabled it for now: https://github.com/sindresorhus/eslint-config-xo/commit/023a7ab5323e5175d4fcd8ca50ed07779473ca8a

**Comment by SamVerschueren** [comment]
Thanks!

**Comment by sindresorhus** [comment]
Seems like it will be fixed in ESLint 4 in a couple of months, so we can just leave this here until then.

**Comment by sindresorhus** [comment]
New version is out: https://github.com/xojs/xo/releases/tag/v0.20.0
