### ISSUE TITLE
Idea: Add `eslint-plugin-security` rules

### ISSUE THREAD

**Issue by Rowno** [xojs/xo#205]
Just an idea, but some of the [eslint-plugin-security](https://github.com/nodesecurity/eslint-plugin-security) rules might be good candidates to add to XO, like `detect-unsafe-regex`, `detect-eval-with-expression` and `detect-non-literal-require`.

**Comment by sindresorhus** [comment]
I looked at it awhile ago and the only interesting rule then was `detect-unsafe-regex`. The other ones are just too naive with too many potential false positives. Maybe also `detect-eval-with-expression`, but everyone knows `eval` is bad, so it won't really help much. I used to have [`no-dynamic-require`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-dynamic-require.md) enabled which is similar to `detect-non-literal-require`, but I ended removing it (https://github.com/sindresorhus/xo/commit/29a5263742f31109cd3fdfd19eb4b3ea0d27de4b), as it was just too annoying. The only time I used dynamic require was when it was the only choice.

I'll keep this open for further discussion, but I'm not entirely convinced yet about adding this plugin just for one rule.

**Comment by Rowno** [comment]
It would be awesome just to have `detect-unsafe-regex` added to XO (in whatever form) since it's such a common security issue in Node.js. I can port it to `eslint-plugin-unicorn` if you want it.

**Comment by sindresorhus** [comment]
> It would be awesome just to have detect-unsafe-regex added to XO (in whatever form) since it's such a common security issue in Node.js.

Agreed, but there are some problems with it, see: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/153
