### ISSUE TITLE
xo can't be closed/terminated

### ISSUE THREAD

**Issue by niftylettuce** [xojs/xo#264]
if xo hangs due to some weird error (which I'm not certain what the error is since the process gets hung), it can't be terminated through `killall` or `kill`, I have to force quit using Activity Monitor for some reason

**Comment by pvdlg** [comment]
Can you provide a way to reproduce this issue? Or at least a link to the project on which it happens with a description of the steps that ends in this situation?

Otherwise with so few information we won't be able to analyze anything.

**Comment by niftylettuce** [comment]
haven't been able to reproduce, but I know that I definitely have had `xo` had issues terminating the process when you CTRL+C it
