### ISSUE TITLE
Fix TODOs in codebase

### ISSUE THREAD

**Issue by sindresorhus** [xojs/xo#289]
Not super important, but we should eventually fix the TODO's in the codebase:

```
  main.js:72:3
  ⚠   72:3  Unexpected todo comment.  no-warning-comments
  ⚠  113:3  Unexpected todo comment.  no-warning-comments
  ⚠  127:2  Unexpected todo comment.  no-warning-comments

  lib/options-manager.js:224:3
  ⚠  224:3  Unexpected todo comment.  no-warning-comments

  4 warnings
```

**Comment by wuweiweiwu** [comment]
@sindresorhus Can i work on this? :)

**Comment by sindresorhus** [comment]
@wuweiweiwu Yes, go ahead :)

**Comment by wuweiweiwu** [comment]
@sindresorhus 

Can you clarify this a bit for me?

```javascript
		// TODO: We need to be able to tell whether it was specified
		// or not as CLI arguments overrides package.json config
		// semicolon: {
		// 	type: 'boolean',
		// 	default: true
		// },
```

Thank you!

**Comment by sindresorhus** [comment]
@wuweiweiwu Ignore that one. It probably needs a change in [`meow`](https://github.com/sindresorhus/meow) as we need to know whether the flag was specified. Since it's listed there as `boolean` with a default value of `false`, it will return as `false` both when not specified and when specified as `--no-semicolon`, which means there is no way to differentiate. Meow probably needs to also return an object with `rawFlags` before the defaults are applied.

**Comment by wuweiweiwu** [comment]
@sindresorhus Another question. 

```
// TODO: This logic needs to be improved, preferably use the same code as ESLint
// user's configs must be resolved to their absolute paths
```

Do you mean the way ESLint finds the config files?

Thank you!

**Comment by pvdlg** [comment]
Regarding this TODO:
```
// TODO: This logic needs to be improved, preferably use the same code as ESLint
// user's configs must be resolved to their absolute paths
```
I don't think we can use the ESLint logic as it wouldn't load plugin required by shareable config due to eslint/eslint#3458.

**Comment by fregante** [comment]
Closing as no longer serving a purpose (those 7 remaining TODOs in the code are more visible than this 2018 issue on the last page) 😅
