### ISSUE TITLE
enhancement: support option --print-config and --debug

### ISSUE THREAD

**Issue by aladdin-add** [xojs/xo#309]

**Comment by sindresorhus** [comment]
Can you elaborate on exactly what these options would do?

**Comment by Aladdin-ADD** [comment]
#### `--debug`

This option outputs debugging information to the console. This information is useful when you're seeing a problem and having a hard time pinpointing it. The ESLint team may ask for this debugging information to help solve bugs.

#### `--print-config`

This option outputs the configuration to be used for the file passed. When present, no linting is performed and only config-related options are valid.

**Comment by sindresorhus** [comment]
I think both of these would be covered by https://github.com/xojs/xo/issues/188.

**Comment by fregante** [comment]
Closing in favor of https://github.com/xojs/xo/issues/188
