### ISSUE TITLE
linting javascript files with no .js extension

### ISSUE THREAD

**Issue by lholmquist** [xojs/xo#313]
After using the `express-generator` to create a new express project, there is a `bin/www` javascript file that is used to run the app.

knowing that there are linting errors, when i run `xo` nothing comes up for that `www` file, which is understandable since from the docs, xo looks looks for javascript files and since there is no extension, doesn't see it.

but if i run `xo bin/www` i still don't see any errors thrown.  If i rename that file to `www.js`, and then run `xo bin/www.js` i see the error output i expect.

I'm just wondering if there is another way of making xo lint this file, or if it is a bug.

**Comment by j0hnm4r5** [comment]
Untested, but you might be able to do it like this (as seen [here](https://github.com/eslint/eslint/issues/4829#issuecomment-251944503)):

```sh
cat bin/www | xo --stdin --stdin-filename=www.js
```

**Comment by fregante** [comment]
XO must rely on the extension to know a file’s content. If it has no extension, it must guess every time. 

Closing this issue as super old. If anyone has it, ask how to address it on eslint’s repo.
