### ISSUE TITLE
Improve documentation for usage with Flow and TypeScript

### ISSUE THREAD

**Issue by jorgegonzalez** [xojs/xo#315]
Although XO does not officially support Flow or TypeScript, they work pretty well with some configuration:

**Flow:**

`npm install --save-dev babel-eslint`
```json
"xo": {
	"parser": "babel-eslint"
}
```

**TypeScript:**

To get TypeScript to work, the `.ts` extension needs to be manually added [here](https://github.com/xojs/xo/blob/master/lib/options-manager.js#L28) first.

`npm install --save-dev typescript-eslint-parser`
```json
"xo": {
	"parser": "typescript-eslint-parser",
	"parserOptions": {
		"typescript": true
	}
}
```

Supporting the `.ts` extension natively would of course be much better than editing the `xo` package in your `node_modules`, and it would be nice if this was all documented in the `readme`.

**Comment by sindresorhus** [comment]
> To get TypeScript to work, the .ts extension needs to be manually added here first.

Have you seen the [`extensions` option](https://github.com/xojs/xo#extensions)?

**Comment by sindresorhus** [comment]
Interested in doing a PR documenting all this?

**Comment by sindresorhus** [comment]
I'd be open to adding an a `typescript: true` option which set's the appropriate config and errors out with a user-friendly error if `typescript` and `typescript-eslint-parser` are not added as devDependencies. Same with Flow, but not as useful as it's much simpler to configure.

**Comment by jorgegonzalez** [comment]
Ah I didn't know about the extensions option. I'll try and work on a PR soon!
