### ISSUE TITLE
xo + prettier not wrapping lines properly to printWidth

### ISSUE THREAD

**Issue by niftylettuce** [xojs/xo#323]
I'm not sure why - but I thought this worked in the past, did something change?

currently have the following code, and after running with `xo --fix` it is not auto-formatting to 80 character print width (see my config for xo/prettier at the bottom of this issue description):

sample JS (I was writing a test with ava)

```js
test('should throw an error if we fail to pass an object `options`', async t => {
  api = new Frisbee(options);
  let error = await t.throws(api.get('', []));
  t.is(error.message, '`options` must be an object');
  error = await t.throws(api.get('', 1));
  t.is(error.message, '`options` must be an object');
});
```

(and when using `xo --fix` it gives the error):

```sh
test/test.node.js|74 col 1 error| Line 74 exceeds the maximum line length of 80. (max-len)
```

but shouldn't this auto-format with `xo --fix` to the following?

```js
test(
  'should throw an error if we fail to pass an object `options`',
  async t => {
    api = new Frisbee(options);
    let error = await t.throws(api.get('', []));
    t.is(error.message, '`options` must be an object');
    error = await t.throws(api.get('', 1));
    t.is(error.message, '`options` must be an object');
  }
);
```

if I do this manually I get the errors:

```sh
test/test.node.js|74 col 6 error| Replace `⏎··'should·throw·an·error·if·we·fail·to·pass·an·object·`options`',⏎·` with `'should·throw·an·error·if·we·fail·to·pass·an·object·`options`',` (prettier/prettier)
test/test.node.js|77 col 1 error| Delete `··` (prettier/prettier)
test/test.node.js|78 col 1 error| Delete `··` (prettier/prettier)
test/test.node.js|79 col 3 error| Delete `··` (prettier/prettier)
test/test.node.js|80 col 3 error| Delete `··` (prettier/prettier)
test/test.node.js|81 col 1 error| Replace `····` with `··` (prettier/prettier)
test/test.node.js|82 col 1 error| Replace `··}⏎` with `}` (prettier/prettier)
```

here's my package.json config relative to xo/prettier:

```json

  "prettier": {
    "singleQuote": true,
    "jsxBracketSameLine": true
  },
  "xo": {
    "prettier": true,
    "parserOptions": {
      "sourceType": "script"
    },
    "rules": {
      "max-len": [
        "error",
        {
          "code": 80,
          "ignoreUrls": true
        }
      ],
      "max-depth": [
        "error",
        6
      ],
      "capitalized-comments": "off",
      "camelcase": "off",
      "no-warning-comments": "off"
    },
    "space": true
  }
```

using xo v0.21.0

seems that `prettier --write` doesn't format it to 80 chars either

**Comment by niftylettuce** [comment]
related:

* https://github.com/xojs/xo/issues/322
* https://github.com/xojs/xo/issues/321
* https://github.com/xojs/xo/issues/320

we can prob close all the other ones (with exception of #320 - probably should actually fix the code there so it merges properly or gives us a better warning about not having both and why)

**Comment by niftylettuce** [comment]
just an update, if I change my `package.json` config to look like this:

```
  "xo": {
    "extends": "prettier",
    "plugins": ["prettier"],
    "parserOptions": {
      "sourceType": "script"
    },
    "rules": {
      "max-len": [
        "error",
        {
          "code": 80,
          "ignoreUrls": true
        }
      ],
      "max-depth": [
        "error",
        6
      ],
      "capitalized-comments": "off",
      "camelcase": "off",
      "no-warning-comments": "off"
    },
    "space": true
  }
```

and add the packages `yarn add -D eslint-plugin-prettier eslint eslint-config-prettier prettier`

the warning goes away about max-len if I manually fix the code with the long string (since prettier doesn't)

**Comment by pvdlg** [comment]
The first line in your code snippet is 82 characters long but Prettier doesn't reformat it.
See https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUByNALCAVwBsATAAhjwCcIB3cgQynLmtuvIEsAzcuuOR6MuxShHIAHRmjRMWEAEYArOGBjkABhEkwu0NJuwAaJmgCeUMJXIBeAHzlgAHRZNJXO+ShwGAMWouNEU4OEwdPQMASgBuV3JyYjgNNg4vRjoRDRgAOipaOjRMRg8cgHNknBNyAG0AXSjY+MocoMxUiGocgFs4WUYK02xtXX0oQ3JuwgxyEPlyJVV1bCa3Ds5bJkyubLyaeiKSrnLK7GqARka4t1y29Z6+tAG4IZHI8c1J6Y055gWVNQwFbXAC+sRAxhAETGaGQoEY7HoAAUEQhYShGAA3CBcUgQkCKaiMMAAa2SAGVpGAuFAysgYNRCC8QDS0GwYEiiWVuoxkMJiGzIco0AAPABCRNJFMYvQAMjS4HzGALmdJqGzqMgCYxFOZiNB8ZJArAAOq4qjIAAcAAZIUaIGyTUTJFqjX02JjFZDqHAAI6ELg+zkDHlKlWQtndLj0xnMtA0spJACKhAg8DDgtQOrNpAtSAATJCGSJiAmAMIQbqhlBQaBekDTOAAFR16P5bJBIKAA

This is easier a bug in Prettier or and intended edge case. Please open an issue over there.

**Comment by pvdlg** [comment]
Closing this issue as XO calls Prettier properly and format according to the Prettier output. 
Please open an issue with Prettier if you think it's a bug.
