### ISSUE TITLE
"npm uninstall xo" doesn't revert test script modification

### ISSUE THREAD

**Issue by yozlet** [xojs/xo#324]
xo's installer changed my `package.json` test script line from
```
"test": "jest"
```
to
```
"test": "xo && jest"
```

... which is great. Unfortunately, `npm uninstall xo` doesn't change it back, so `npm test` is now broken.

I realise that there are all kinds of potential edge cases here depending on what that `test` entry might be at the time of uninstallation, but the basic case should be easy to handle.

(Please be assured that my uninstallation of xo was only temporary. Love you. Miss you. Mean it.)

**Comment by sindresorhus** [comment]
I think that would be weird because `npm install` doesn't add `xo` to the `test` script, `xo --init` does, so `npm uninstall` shouldn't remove it either.

**Comment by yozlet** [comment]
Ah, thank you - I hadn't realised that. I'm happy to close this, or relabel as an enhancement (`npm uninstall` should warn/remind the user to remove `xo` from `test` if it's there)
