### ISSUE TITLE
XO Documentation on overrides misleading

### ISSUE THREAD

**Issue by devtanc** [xojs/xo#328]
The docs show this structure:

```json
{
	"xo": {
		"semicolon": false,
		"space": 2,
		"overrides": [
			{
				"files": "test/*.js",
				"esnext": false,
				"space": 3
			},
			{
				 "files": "test/foo.js",
				 "esnext": true
			}
		]
	}
}
```

But no matter how I formatted things, it never worked until I used this structure, with the "rules" property specified:

```json
{
	"xo": {
		"semicolon": false,
		"space": 2,
		"overrides": [
			{
				"files": "test/*.js",
				"rules": {
					"esnext": false,
					"space": 3
				}
			},
			{
				"files": "test/foo.js",
				"rules": {
					"esnext": true
				}
			}
		]
	}
}
```

I think the docs need to be updated to reflect that

**Comment by pvdlg** [comment]
@simonhaenisch that's normal, because `no-console` is a rule, so it should be under `rules` (whether it's an override or not).
`space`, `semicolon` and `esnext` are XO option. They should go directly under the `xo` config object or under each override.
@devtanc I just tried what you report on a sample project and it works as expected with the configuration from the doc. The overrides are applied in the the order in which they are defined (so if a file is matched by multiple overrides, the config used is a merge of the matches).

**Comment by devtanc** [comment]
File structure:
```
root
  |-- test
       |-- functions
            |-- hierarchy
                 |-- utils
                     |-- index.test.js
```
this doesn't work

```js
  "xo": {
    "prettier": true,
    "env": ["node", "mocha"],
    "plugins": ["node", "unicorn"],
    "rules": {
      "camelcase": 0
    },
    "overrides": [
      {
        "files": ["test/**/*.test.js"],
        "no-unused-expressions": 0
      }
    ]
  },
```

this works:

```js
  "xo": {
    "prettier": true,
    "env": [
      "node",
      "mocha"
    ],
    "plugins": [
      "node",
      "unicorn"
    ],
    "rules": {
      "camelcase": 0
    },
    "overrides": [
      {
        "files": [
          "test/**/*.test.js"
        ],
        "rules": {
          "no-unused-expressions": 0
        }
      }
    ]
  },
```
I get this message:
> `✖   25:5   Expected an assignment or function call and instead saw an expression.                                       no-unused-expressions`

And this is the section of that test file:
```js
  it('return undefined if no org exists', () => {
    const org = hierarchy.findOrgByLocation(hierarchyMock, 'NotAnOrgLocation')

    expect(org).to.be.undefined
  })
```

**Comment by pvdlg** [comment]
As explained before `no-unused-expressions` is an ESLint rule, therefore it goes under `rules` (for both the main config and an overrides config).
In your first comment you mentioned `esnext` and `space` that are XO options which go directly un the `xo` config object or under the `override` object.

So the documentation is correct.

**Comment by devtanc** [comment]
Oh I see. Yeah, the esnext and the space were just what was in the docs. Thanks for the clarification.
