### ISSUE TITLE
Rule request: JSX indentation and tag positioning

### ISSUE THREAD

**Issue by fregante** [xojs/xo#337]
These are _just dandy_ for the linter, but they shouldn't be

```jsx
const a = <span>
	text</span>;

const b = get(<span
	href="a"
>text
</span>
);
```

These would be preferred:

```jsx

const a = <span>text</span>;
const a = (
	<span>
		text
	</span>
);

const b = get(
	<span href="a">
		text
	</span>
);
const b = get(
	<span
		href="a"
	> // unsure about this
		text
	</span>
);

**Comment by sindresorhus** [comment]
@bfred-it Anything in https://github.com/yannickcr/eslint-plugin-react we could use?

**Comment by bfred-it** [comment]
These should fix all the issues

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md

**Comment by fregante** [comment]
On my example:
```jsx
const a = <span>
	text</span>;

const b = get(<span
	href="a"
>text
</span>
);
```

With `eslint-config-xo-react` I get:

```js
  ✖  1:11  Missing parentheses around multilines JSX                                      react/jsx-wrap-multilines
  ✖  2:6   Closing tag of a multiline JSX expression must be on its own line.             react/jsx-closing-tag-location
  ✖  6:1   The closing bracket must be aligned with the opening tag (expected column 15)  react/jsx-closing-bracket-location
  ✖  7:1   Expected closing tag to match indentation of opening.                          react/jsx-closing-tag-location
```

Then autofixed to:

```jsx
const a = (
	<span>
		text
	</span>
);

const b = get(<span
	href="a"
>text
</span>
);
```

```js
  ✖   9:1   The closing bracket must be aligned with the opening tag (expected column 15)  react/jsx-closing-bracket-location
  ✖  10:1   Expected closing tag to match indentation of opening.                          react/jsx-closing-tag-location
```

So the rules work, except a couple missing fixes and with a wrong suggestion (`(expected column 15)`???)

The closest, semi-auto-fixed non-erroring version is:

```jsx
const b = get(
	<span
		href="a"
	>text
	</span>
);
```

Close enough! Just `text` is in the wrong position.

**Comment by fregante** [comment]
I can't f#n believe I opened this almost 2 years ago.
