### ISSUE TITLE
CLI ignores specified number for `--space` option

### ISSUE THREAD

**Issue by noahbrenner** [xojs/xo#339]
I just updated to `0.21.1` from `0.18.2` (got a bit behind!). Now, `xo` is responding to the `--space` option, but is *not* using the optional number passed to it:

```bash
$ cat test.js
module.exports = {
    foo: 'bar'
};

$ xo --space=4 test.js

  test.js:2:1
  ×  2:1  Expected indentation of 2 spaces but found 4.  indent

  1 error
```

- Note that `xo` *is* processing the argument, since it's expecting spaces instead of tabs, but it's using the default 2, instead of the specified 4.
- There are no other files in the directory where I did this test.
- There is no `package.json` in this directory or in any of its ancestors.

### What I'm running:

```bash
$ xo --version
0.21.1

$ node --version
v10.6.0
```

I ran most of my tests on 32 bit Windows 7. I get the same `xo` output whether I run this from git bash, PowerShell, or cmd. I also tried it in bash on Linux Mint 18.2 and got the same thing.

I initially ran across the issue when setting up Syntastic with these lines in my `.vimrc`:

```vim
Plug 'sindresorhus/vim-xo'
let g:syntastic_javascript_checkers = ['xo']
let g:syntastic_javascript_xo_args = '--space=4'
" I also tried replacing the line above with this:
let g:syntastic_javascript_xo_lint_args = '--space=4'
```

### Some things I've tried:

- Using a space instead of `=`.
- Quoting the `4`.
- Quoting the whole `--space=4` string.
- Putting the option after the filename (this entirely ignored the option and used the default setting of tab indentation).
- Running `xo` without arguments or with only the filename as an argument also defaulted to expecting tabs.

I'm questioning my memory slightly, but I'm pretty sure that `0.18.2` did not have this behavior and *did* accept the 4-space setting.

### My theory on the cause

The `space` option is defined as type `string` in [main.js](https://github.com/xojs/xo/blob/master/main.js#L71).

However, in [lib/options-manager.js](https://github.com/xojs/xo/blob/master/lib/options-manager.js#L127), the option is only used if it is a `number`, otherwise defaulting to `2`.

I'm happy to submit a pull request for this, if you'd like. Do you have a preference for where to coerce the argument to a number? From my overview, it looks like the options would be `main.js`, `lib/options-manager.js`, or `index.js`.

**Comment by sindresorhus** [comment]
> I'm happy to submit a pull request for this

Great! That would be most welcome :)

Would be good to have a CLI test for this so we don't regress in the future. https://github.com/xojs/xo/blob/master/test/cli.js

> Do you have a preference for where to coerce the argument to a number?

Should be done here: https://github.com/xojs/xo/blob/71d06a0849711946221106bd1748a6485c2968fa/main.js#L116

**Comment by noahbrenner** [comment]
Sounds great, I'll get working on that!
