### ISSUE TITLE
How can I override `parserOptions`

### ISSUE THREAD

**Issue by iwata** [xojs/xo#349]
I'll use `xo` to lint `*.vue` files by `bable-eslint` and `eslint-plugin-vue`.
So, I need to override `parserOptions` like this.
https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error
Please tell me how to do it.

**Comment by pvdlg** [comment]
You can set the option directly under the `xo` property in your `package.json` or you can create a shareable config and set it there, similarly to https://github.com/xojs/eslint-config-xo-react/blob/master/index.js#L3

@sindresorhus should we create a `eslint-config-xo-vue` repo similar to `eslint-config-xo-react`?
Maybe we could start with the `plugin:vue/recommended` preset and `parserOptions`.
We would also need to add `.vue` files support to XO, similarly to the way we added `.ts`.

**Comment by iwata** [comment]
@pvdlg 

> You can set the option directly under the xo property in your package.json

Thanks, I worked as I was told and it worked fine.

> should we create a eslint-config-xo-vue repo similar to eslint-config-xo-react?

I think that it would be very useful.

**Comment by bfred-it** [comment]
> You can set the option directly under the `xo` property in your `package.json`

⚠️ This isn't documented in the readme

**Comment by ChocPanda** [comment]
```json
  "xo": {
    "prettier": "true",
    "extends": [
      "plugin:vue/recommended"
    ],
    "extensions": [
      ".js",
      ".vue"
		],
    "ignores": [
      "reports/**/*",
      ".nyc_output/**/*"
    ]
  }```

**Comment by fregante** [comment]
This way of overriding `parserOptions` seems to work:

```json5
{
  "xo": {
    "envs": [ /* examples */
      "browser",
      "webextensions"
    ],
    "parserOptions": {
      "ecmaScript": 3 /* Test this, you'll see weird new error pop up */
    }
  }
}
```
