### ISSUE TITLE
import/newline-after-import inaccuracies

### ISSUE THREAD

**Issue by artivilla** [xojs/xo#362]
Test Repo: https://github.com/artivilla/personal-starter/pull/1
Run `npm lint` that runs xo has 2 issues:

- `import/newline-after-import` is being report on [line 7](https://github.com/artivilla/personal-starter/pull/1/files#diff-d40ca498570c011efba7592b9ec44b07R7) and there is a newline present.
- Should not lint files outside `src/` dir.

**Comment by sindresorhus** [comment]
> import/newline-after-import is being report on line 7 and there is a newline present.

This needs to be reported on https://github.com/benmosher/eslint-plugin-import

> Should not lint files outside src/ dir.

Weird. I'll look into it.

**Comment by artivilla** [comment]
I think this can be closed. So the reason it's doing that is b/c it's throwing this in my lint-staged so I need to set the key as src/**/* as such:
```
 "lint-staged": {
    "src/**/*.js": [
      "xo src --ext .js",
      "prettier --write",
      "git add"
    ]
  },
```
Thanks for all your amazing work! 🦄
