### ISSUE TITLE
Add trailing indentation to all padding lines - trailing-indent-padded-line

### ISSUE THREAD

**Issue by Yzrsah** [xojs/xo#379]
I'm looking for a code formatter that is friendly to a convention that I standardize on:
```
const f = x => {
	// something
	g(x)
👉
	// something else
	h(x)
}
```
The **👉** indentation is required to match the block scope.

# Rule

If there's an empty padded line, it is required to be indented to the same level as the block scope.

# Why?

- Editors don't allow you to click on the empty space and get a cursor at the indent level.
- You typically have to move to the empty line at column 0, then press tab to re-tabulate,
*or*
- You typically have to move to the end of the previous line, then press enter. *Just to invoke smart behavior to try to repair the missing indentation on the next line*
- Every IDE has a different behavior for adjusted automatic indentation on empty lines to deal with this problem.

# Much, much better:

- Adding trailing indentation to empty padding lines resolves all issues.
- It does not behave differently in IDE's and does not require special behavior. You don't have to think about how the IDE works.
- Your cursor is always at the right indent level.
- Your cursor is always "ready" at the location you will begin typing the code.
- It doesn't break any code or cause any problems with anything.
- You don't have to re-indent, or move your cursor to the previous line and press enter, or do anything.
- You can paste on the empty line without being at the wrong indent level.

**Comment by fregante** [comment]
You’re asking for a lint rule or for an adjustment to the existing rule. XO isn’t the place for either

**Comment by fregante** [comment]
You’re asking for a lint rule or for an adjustment to the existing rule. XO isn’t the place for either
