### ISSUE TITLE
string support for backticks

### ISSUE THREAD

**Issue by hanakin** [xojs/xo#380]
currently when I use backticks for strings xo flags it as an error wanting single quotes and furthermore converts it to single quotes when I fix on save. My env both globally and in the file via a flag is set to es6

**Comment by sindresorhus** [comment]
It only allows temple literals when they’re actually useful, meaning the string has interpolation or multiple lines.

**Comment by hanakin** [comment]
`:value[3]:`

is using interpolation but still gets flagged

**Comment by sindresorhus** [comment]
I really doubt that. Can you show an example?
