### ISSUE TITLE
Using `"parser": "babel-eslint"` crashes the server part of vscode-linter-xo

### ISSUE THREAD

**Issue by joakimbeng** [xojs/xo#382]
I'm using XO with VS Code using the [vscode-linter-xo](https://github.com/SamVerschueren/vscode-linter-xo) plugin and it works splendid in some projects but not at all in others.

This is the log output from "XO Linter" in VS Code:

```
Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper[37255]: ../../vendor/node/src/node_contextify.cc:751:static void node::contextify::ContextifyScript::CreateCachedData(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) >= (1)' failed.
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::Assert(char const* const (*) [4]) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: node::contextify::ContextifyScript::CreateCachedData(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::VirtualMemory::TakeControl(v8::internal::VirtualMemory*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: 0x3a08a17842fd
[Error - 20:52:34] Connection to server got closed. Server will not be restarted.
```

I finally tracked it down to being caused by using another parser than the default, e.g. in my case setting `"parser": "babel-eslint"`. I thought this might be related to the VS Code plugin not being able to resolve the parser correctly, and it appears to be the case.

When I change [lib/options-manager.js](https://github.com/xojs/xo/blob/21e7b576f361681d8bb4ff4ed722e1d8f19d1e7d/lib/options-manager.js#L254) like so:

```diff
diff --git a/node_modules/xo/lib/options-manager.js b/node_modules/xo/lib/options-manager.js
index f9758ae..0045b87 100644
--- a/node_modules/xo/lib/options-manager.js
+++ b/node_modules/xo/lib/options-manager.js
@@ -248,7 +248,7 @@ const buildConfig = options => {
 	}
 
 	if (options.parser) {
-		config.baseConfig.parser = options.parser;
+		config.baseConfig.parser = resolveFrom(options.cwd, options.parser);
 	}
 
 	if (options.extends && options.extends.length > 0) {
```

The issue goes away and now all of my projects with XO is working fine in VS Code.

I don't know if this fix is breaking something else. What do you think? If not I can make a PR for this if you'd like me to. Or can/should this be fixed in the VS Code plugin somehow?

---

xo version: 0.24.0
node version: 10.15.1

**Comment by sindresorhus** [comment]
`config.baseConfig` is passed directly into ESLint, which is in charge of resolving the parser location, so it should *just work*, without having to resolve upfront. Maybe the `cwd` is not correctly set somewhere else.

**Comment by joakimbeng** [comment]
Hmm, yes it seems I was to quick in posting this...
I found another one of my projects where it still does not work, despite having the same versions of every dependency and a similar XO config. I'll continue investigating and close this then 😆
