### ISSUE TITLE
Document how to use XO with Vue

### ISSUE THREAD

**Issue by ChocPanda** [xojs/xo#387]
Hi All,

Would you consider adding support/some config for use in VueJS applications?

**Comment by sindresorhus** [comment]
I would be happy to add docs on how to use XO with Vue, but I'm not interested in adding built-in support.

It's probably enough to set the `plugins`, `parser`, and `extensions` options.

https://github.com/vuejs/eslint-plugin-vue

**Comment by ChocPanda** [comment]
I would appreciate the documentation as I tried adding the plugins and stuff but couldn't get it working properly. Would you not consider a shareable eslint config similar to the react 1?

**Comment by ChocPanda** [comment]
@sindresorhus so I tried your suggestion and there were quite a few incompatibilities in xo and the default vue configuration so I created https://www.npmjs.com/package/eslint-config-xo-vue. Would you be okay with me creating a PR to your documentation to encourage people to give it a try?

**Comment by sindresorhus** [comment]
Sure :)
