### ISSUE TITLE
How to specify --rulesdir to have local rules

### ISSUE THREAD

**Issue by fregante** [xojs/xo#391]
How can I have a custom rule? eslint offers the `--rulesdir` flag:
https://eslint.org/docs/user-guide/command-line-interface#specifying-rules-and-plugins

More info:https://eslint.org/docs/developer-guide/working-with-rules#runtime-rules

**Comment by sindresorhus** [comment]
Not at the moment. I never added it as I personally never needed it and nobody else has requested it. Usually, it's better to just create a shareable config instead.

PR welcome for a `--rules-directory` flag.

**Comment by fregante** [comment]
Related: https://github.com/xojs/xo/issues/428

**Comment by fregante** [comment]
No interest anymore, probably the new config will fix this

- https://github.com/xojs/xo/issues/702
