### ISSUE TITLE
Don't auto-fix `.onmessage` in `prefer-add-event-listener` rule

### ISSUE THREAD

**Issue by psiinon** [xojs/xo#400]
`xo --fix` changes `onmessage` events to use `addEventListenner`.
However `onmessage` events automatically call the `port.start()` method, while if they are added by addEventListenner then `start()` has to be called manually, as per https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent : 
```
If the onmessage event is attached using addEventListener, the port is manually started using its start() method:
```
Using `xo --fix` broke our app until we worked this out and added the calls to start the relevant ports.
The `--fix` option should not break anything - it should either leave the `onmessage` events as they are or add the relevant `start()` calls in.

**Comment by sindresorhus** [comment]
Moving this over to https://github.com/sindresorhus/eslint-plugin-unicorn/issues/537.
