### ISSUE TITLE
`xo --space` doesn't work with `eslint-config-xo-typescript`

### ISSUE THREAD

**Issue by haotangio** [xojs/xo#410]
I tried to use `xo --space` together with `eslint-config-xo-typescript` but it doesn't work.
Seems like we need to change the currently hardcoded tab-indent usage of `eslint-config-xo-typescript`

**Comment by dobromyslov** [comment]
Workaround:

Add to package.json:
`
"xo": {
  "space": 2,
  "rules": {
      "@typescript-eslint/indent": "off"
    }}
`

**Comment by pvdlg** [comment]
That should have been fixed wit the recent changes to support TypeScript out of the box: https://github.com/xojs/xo/blob/ad2a71228dbef9cdb41374ce7abf481d5fc5f3d8/lib/options-manager.js#L291

@haotangio @dobromyslov can you try again with the latest XO version?
Note that you shouldn't configure `eslint-config-xo-typescript` anymore as it will now be used automatically for `.ts`/`.tsx` files.
