### ISSUE TITLE
Not fixing mixed tabs and spaces

### ISSUE THREAD

**Issue by dnl-brnr** [xojs/xo#412]
When a given line offends the `no-mixed-spaces-and-tabs` rule, `xo --fix` doesn't automatically fix it, it just throws an error.

Similarly, if a line is over-indented, for example:

```
function foo() {
			return 'foo'
}
```

`xo --fix` neither fixes it or throws an error.

**Comment by sindresorhus** [comment]
The behavior of the rule is determined by ESLint, so you should open an issue there instead: https://github.com/eslint/eslint/issues
