### ISSUE TITLE
Module order detection bug

### ISSUE THREAD

**Issue by Richienb** [xojs/xo#424]
In a recent update, for Linux `xo` tries to make `require(".")` happen **after** other requires. However, for Windows `xo` tries to make it happen **before** other requires.

See https://travis-ci.org/sindresorhus/figures/jobs/649856894#L82-L86

cc @sindresorhus

**Comment by sindresorhus** [comment]
This was actually fixed in XO 0.26.0.

**Comment by Richienb** [comment]
Affirmative. Thanks!
