### ISSUE TITLE
Use and extend eslint's config files instead of mapping it to XO's own schema

### ISSUE THREAD

**Issue by fregante** [xojs/xo#428]
Some options are XO-specific, like `space: true`, but many of them (including rules and such) don't need to be customized to XO's own format.

An example of this is https://github.com/xojs/xo/issues/319. This issue wouldn't exist at all if, instead of having a `xo.globals` key in package.json, XO just used `eslintConfig.globals`

This is particularly painful when copying configuration from internet and then having to match it to XO.

This is fine, it's the same for both XO and eslint:

```js
{
	rules: {
		"no-console": "off"
	}
}
```

But what about this? From: https://github.com/sveltejs/eslint-plugin-svelte3

```js
{
    overrides: [
      {
        files: ["**/*.svelte"],
        processor: "svelte3/svelte3"
      }
    ]
}
```

eslint has that `processor` property, XO doesn't. I still haven't figured this out.

---

It's great that XO offers shortcuts for common configuration, but could it leave eslint's config in eslint's files?

This is an example package.json for a random project (no need to read it):

```json
{
  "xo": {
    "space": true,
    "rules": {
      "import/no-unassigned-import": 0,
      "no-new": 0
    },
    "plugins": [
      "svelte3"
    ],
    "envs": [
      "browser",
      "webextensions"
    ],
    "parserOptions": {
      "ecmaVersion": 2019,
      "ecmaFeatures": {
        "jsx": false
      }
    },
    "extensions": [
      "svelte"
    ],
    "overrides": [
      {
        "files": ["**/*.svelte"],
        "processor": "svelte3/svelte3" /* Doesn't work */
      }
    ]
  }
}
```

95% of this isn't XO-specific. I reckon it should be written as:

```json
{
  "xo": {
    "space": true,
    "extensions": [
      "svelte"
    ]
  },
  "eslintConfig": {
    "rules": {
      "import/no-unassigned-import": 0,
      "no-new": 0
    },
    "plugins": [
      "svelte3"
    ],
    "envs": [
      "browser",
      "webextensions"
    ],
    "parserOptions": {
      "ecmaVersion": 2019,
      "ecmaFeatures": {
        "jsx": false
      }
    },
    "overrides": [
      {
        "files": ["**/*.svelte"],
        "processor": "svelte3/svelte3"
      }
    ]
  }
}
```

Being a thinner wrapper around eslint frees XO from having to document overlapping features. Does [XO's readme](https://github.com/xojs/xo) really need to document `envs`, `globals`, `ignores`, `rules`, `plugins`, `extends`, `settings`, and `parser`? Yep, that's most of them.

The CLI could do a similar job at mapping unrecognized flags back to eslint (risky but better than having no chance at all)

---

This is a pretty big change at this point, but ideal for a XO 1.0 nonetheless.

**Comment by sindresorhus** [comment]
I feel like ESLint has way too many options and CLI flags and I don’t want to overload users with all that. I also see value in being able to add custom behavior to options when we can improve upon ESLint. I’m happy to add support for reading from `eslintConfig` in package JSON too, but I don’t want to remove the XO options.

**Comment by pvdlg** [comment]
What would be the point of splitting the XO only and the ESLint config?
Currently you can use any ESLint option in the XO config and it will be passed down to ESLint, even if it's an override.

With the example you gave:
 ```
{
    overrides: [
      {
        files: ["**/*.svelte"],
        processor: "svelte3/svelte3"
      }
    ]
}
```
I tested and the `processor` option is passed down to [CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine).

The only exceptions are `envs` and `globals` that can be configured either as an array or an object in ESLint by only as array in XO.
Other than those two you can just copy/paste any ESLint config into the XO config and it will work.

One more thing regarding file extension. XO since `0.27.0` glob the files first and then look for configuration files based on the files being linted. That mean if you call `xo` without specifying a glob pattern or the `--extension` option it will only retrieve `ts`, `js`, `tsx` and `jsx` files.
In your case you would have to call xo with `xo --extension svelte`

**Comment by fregante** [comment]
The last sentence might be why the configuration wasn’t working for me. 

> What would be the point of splitting the XO only and the ESLint config?
> Currently you can use any ESLint option in the XO config and it will be passed down to ESLint, even if it's an override.

You answered yourself. That’s not documented, why would anyone expect that XO’s options are also silently ESLint options? Wouldn’t it make more sense to make this more explicit by having the user put ESLint options in ESLint’s config files?

XO is meant to provide defaults and make linting easier for the end user, but the “thicker” the layer around ESLint the more documentation you have to write and keep up to date around it, or else you’ll end up like this.

> I feel like ESLint has way too many options and CLI flags and I don’t want to overload users with all that.

You can still *suggest* a handful of options without making it look like they’re specific to XO.

**Comment by fregante** [comment]
> What would be the point of splitting the XO only and the ESLint config?

With the upcoming _[Flat Configmageddon](https://github.com/eslint/eslint/issues/13481)_ I think reducing your XO-specific config would be your first priority. I think your choices are:

- leave xo.config unchanged and further widen the gap that this issue and [#447](https://github.com/xojs/xo/issues/447) shows
- rework xo.config trying to match the new config format
- get rid of everything except XO-native config like `--space`, `--prettier` and so on.

Related:

- https://github.com/xojs/xo/issues/122
- https://github.com/xojs/xo/issues/646
- https://github.com/xojs/xo/issues/447
- https://github.com/xojs/xo/issues/272

**Comment by fregante** [comment]
Closing as non-actionable. Further discussion available in:

- https://github.com/xojs/xo/issues/702#issuecomment-2312419604
- https://github.com/eslint/eslint/issues/18800

This issue can be considered folded into: 

- https://github.com/xojs/xo/issues/702
