### ISSUE TITLE
Something wrong with spaces between curly braces

### ISSUE THREAD

**Issue by lcdss** [xojs/xo#440]
When `xo` is executed, for some reason, it thinks all curly braces shouldn't have spaces and it can't fix the code even if there is nothing to fix. If I remove the spaces, it complain about the `object-curly-spacing` rule, and if I add the spaces (prettier already add them automatically on save), it still fails. Anyone knows why this is happening?

```js
import { render, unmountComponentAtNode } from 'react-dom';
import { render } from 'react-dom';
import React, { useEffect, useState } from 'react';

const letters = { a: 'a', b: 'b' };
```

```bash
var/www/client $ yarn lint
yarn run v1.21.1
$ xo

  tests/app.test.js:3:9
  ✖  3:9   Replace ·render,·unmountComponentAtNode· with render,·unmountComponentAtNode  prettier/prettier

  ✖  10:20  Replace ·a:·'a',·b:·'b'· with a:·'a',·b:·'b'                                  prettier/prettier

  src/index.js:4:9
  ✖  4:9   Replace ·render· with render                                                  prettier/prettier

  src/app.js:3:16
  ✖  3:16  Replace ·useEffect,·useState· with useEffect,·useState                        prettier/prettier

  3 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```json
{
  "xo": {
    "envs": [
      "browser",
      "es2020",
      "mocha"
    ],
    "extends": [
      "xo-react"
    ],
    "prettier": true,
    "rules": {
      "import/extensions": [
        "error",
        {
          "css": "always"
        }
      ],
      "import/no-unassigned-import": [
        "error",
        {
          "allow": [
            "**/*.css"
          ]
        }
      ],
      "object-curly-spacing": [
        "error",
        "always"
      ],
      "unicorn/catch-error-name": "off"
    }
  }
}
```

```json
{
  "printWidth": 80,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all"
}

```

**Comment by papb** [comment]
Hello, I have just faced this problem as well, and found the solution. Sadly, XO infers rules from prettier in a way that I don't think is correct. [From readme](https://github.com/xojs/xo#prettier):

> ### prettier
> 
> Type: `boolean`\
> Default: `false`
> 
> Format code with [Prettier](https://github.com/prettier/prettier).
> 
> The [Prettier options](https://prettier.io/docs/en/options.html) will be read from the [Prettier config](https://prettier.io/docs/en/configuration.html) and if **not set** will be determined as follow:
> - [semi](https://prettier.io/docs/en/options.html#semicolons): based on [semicolon](#semicolon) option
> - [useTabs](https://prettier.io/docs/en/options.html#tabs): based on [space](#space) option
> - [tabWidth](https://prettier.io/docs/en/options.html#tab-width): based on [space](#space) option
> - [trailingComma](https://prettier.io/docs/en/options.html#trailing-commas): `none`
> - [singleQuote](https://prettier.io/docs/en/options.html#quotes): `true`
> - [bracketSpacing](https://prettier.io/docs/en/options.html#bracket-spacing): `false` **<<<===== See this**
> - [jsxBracketSameLine](https://prettier.io/docs/en/options.html#jsx-brackets): `false`
> 
> If contradicting options are set for both Prettier and XO an error will be thrown.

Instead of using prettier defaults, XO has basically overwritten some of them. So you have to update your prettier config, adding `bracketSpacing` explicitly:

```diff
{
  "printWidth": 80,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
+ "bracketSpacing": true,
  "trailingComma": "all"
}
```

**Comment by lcdss** [comment]
Thanks for sharing the solution. I opted to configure eslint + prettier manually for this specific project but next time I'Il try it again.
