### ISSUE TITLE
Extraneous newline at EOF with `--stdin --fix`

### ISSUE THREAD

**Issue by charlesbjohnson** [xojs/xo#459]
👋

I noticed a very tiny issue when using `--stdin --fix` where an additional newline is added to the end of the input.

```sh
$ cat foo.js
console.log(1)

$ cat foo.js | npx xo --stdin --fix
console.log(1);


$
```

It's not a big deal, but it can be annoying when `xo` is used to automatically format buffers in an editor (ie. https://github.com/dense-analysis/ale).

It seems that this line of code is responsible for the additional newline:

https://github.com/xojs/xo/blob/87e3615e3f17defeade1bab550a64a04911157ab/cli-main.js#L160

Would you accept a PR to change this to `process.stdout.write`?

**Comment by sindresorhus** [comment]
PR welcome :)
