### ISSUE TITLE
Report errors as GitHub Actions Annotations

### ISSUE THREAD

**Issue by fregante** [xojs/xo#465]
Apparently if you run ESLint on GitHub Actions it automatically changes the output and GitHub reports the errors inline:

<img width="662" alt="Screen Shot 2020-04-18 at 12 13 32" src="https://user-images.githubusercontent.com/1402241/79634976-31327f00-816e-11ea-9863-81378c3622d4.png">

On my computer
```
$ eslint .

./packages/helper-settings/components/checkbox.js
  13:7  error  Form label must have ALL of the following types of associated control: nesting, id  jsx-a11y/label-has-for

✖ 1 problem (1 error, 0 warnings)
```

On GHA:

```
$ eslint .

/home/runner/work/OctoLinker/OctoLinker/packages/helper-settings/components/checkbox.js
##[error]  13:7  error  Form label must have ALL of the following types of associated control: nesting, id  jsx-a11y/label-has-for

✖ 1 problem (1 error, 0 warnings)
```

I can't find any references to it in ESLint’s code and repo, but it appears to happen automatically. Real life example: [PR Actions tab](https://github.com/OctoLinker/OctoLinker/pull/895/checks?check_run_id=596965393), [PR Files tab](https://github.com/OctoLinker/OctoLinker/pull/895/files#diff-7ed373a9d8450195e9632d0c184d41fdR13)

Here's [the docs](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message), but it doesn't seem to match ESLint's output (`##[error]` vs `::error`)

My guess is that GHA is configured to automatically use a different reporter for ESLint, rather than being a feature of ESLint itself.

**Comment by sindresorhus** [comment]
Good idea. This would be nice indeed.

**Comment by fregante** [comment]
I think this is done with Problem Matchers: https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

I wonder if this would be as easy as using eslint’s default formatter. Is XO’s formatter easily replaceable? e.g. `if is_GHA, formatter = eslint/formatter`

**Comment by sindresorhus** [comment]
@fregante XO supports any formatter that ESLint supports.
