### ISSUE TITLE
Allow brace-less conditions around for loops (`curly`)

### ISSUE THREAD

**Issue by fregante** [xojs/xo#467]
This rule rightfully enforces using curly braces around blocks: https://eslint.org/docs/rules/curly

However I think sometimes it makes code unnecessarily nested. 

## Currently
```js
if (isIterable(foo)) {
	for (const bar of foo) {
		log(bar);
	}
}
```

```js
for (const bar of foo) {
	if (bar.isAttached) {
		log(bar);
	}
}
```
## Ideal

```js
if (isIterable(foo)) for (const bar of foo) {
	log(bar)
}
```
```js
for (const bar of foo) if (bar.isAttached) {
	log(bar);
}
```

---

The rule doesn't have this exception yet, so I'm proposing it here to discuss it.

**Comment by fregante** [comment]
Swift 2 also has a specific syntax for the second example:

```swift
for bar in foo where bar.isAttached {
   ...
}
```

**Comment by sindresorhus** [comment]
This is the same as the semicolon discussion. I really don't think we should embrace quirks in JS. I don't even use `where` much in Swift as it makes it harder to add more conditions/logic later on (which is your argument for https://github.com/xojs/eslint-config-xo/pull/60).

**Comment by fregante** [comment]
I don’t think this is the same as the semicolons. I made several arguments for that, it’s hardly a quirk. 

For this one, sure, my concern was the line becoming too long and effectively having 2 statements on a line.

**Comment by sindresorhus** [comment]
> it’s hardly a quirk.

🤷‍♂️It's definitely not expected behavior either. It's not like this pattern is in any JavaScript books/tutorials. `where` in Swift is a documted feature.

**Comment by fregante** [comment]
Oops, you said semicolons. I thought you were talking about something else 😅
