### ISSUE TITLE
eslint-plugin-istanbul

### ISSUE THREAD

**Issue by coreyfarrell** [xojs/xo#477]
A few days ago I published [eslint-plugin-istanbul](https://github.com/istanbuljs/eslint-plugin-istanbul#readme).  I'm not sure if this is something `xo` would be interested in adding to the next major (either as an error or just a warning).  Feel free to close this if you are not interested, just figured it was worth announcing.

**Comment by sindresorhus** [comment]
`prefer-ignore-reason ` could maybe be useful. However, the plugin is fairly immature and I don't want to deal with early issues, so let's revisit this later when the plugin is more mature.

**Comment by coreyfarrell** [comment]
This is reasonable, thanks for responding.  Up to you if you want to close this issue or leave it open so users can potentially see it and test on their own.

Just to share the current plan I think `prefer-ignore-reason` and `no-ignore-file` will never change what they report.  `prefer-ignore-reason` will never be fixable.  I'm not sure if `no-ignore-file` should be fixable or not.  If that decision is made it will be made before 1.0.0 and will be listed as a breaking change.

**Comment by fregante** [comment]
Plugin dormant. Useful rule covered by https://github.com/xojs/xo/issues/571
