### ISSUE TITLE
Request: some description of rules

### ISSUE THREAD

**Issue by rstacruz** [xojs/xo#48]
standard has a [RULES.md](https://github.com/feross/standard/blob/master/RULES.md) as an overview of what's enforced. Can `xo` have something similar? I'd like to know how xo differs from, say, semistandard.

**Comment by sindresorhus** [comment]
Yes, I've been meaning to write a style guide kind of thing, but haven't had the time yet.

Would be so cool if someone would make a style guide generator based on ESLint config.

**Comment by sindresorhus** [comment]
You can see an overview of the differences between XO and Standard here: https://github.com/feross/standard/issues/216#issuecomment-127569835

**Comment by fregante** [comment]
It's been 7 years, I don’t think this will ever be written, there are _too many rules_
