### ISSUE TITLE
Issue with type definitions in TypeScript

### ISSUE THREAD

**Issue by matt81093** [xojs/xo#481]
After working on this for a time, I came to the conclusion that for XO to parse it correctly (even with listed TypeScript support), I need to manually change the parser inside the config file?

If this is the case, I assume this is just a small documentation issue, but I haven't come across anything referencing changing the parser. I did come across issue: #215 which redirected me to try changing the parser to `babel-eslint`

Otherwise, an example of the issue is `function (myArg: string) : myClass {` with `: string` being noted as incorrect and giving a syntax error. (Files with extension .ts)

**Comment by sindresorhus** [comment]
XO automatically uses the TypeScript parser for TypeScript files.

**Comment by matt81093** [comment]
Any idea offhand why I would be getting a `parsing error: unexpected token :` message?

**Comment by matt81093** [comment]
`*.d.ts` files are parsing correctly, but `*.ds` are not.

**Comment by matt81093** [comment]
I'm now leaning towards this package using an old version of xo for some reason. Still attempting to figure out how it acquires xo.

**Comment by matt81093** [comment]
Still not working, but not important at the moment to me either. Closing.
