### ISSUE TITLE
Error: 'path' should be listed in the project's dependencies.

### ISSUE THREAD

**Issue by saneef** [xojs/xo#482]
I'm getting below error on a fresh project.

```bash
> xo index.js

  index.js:1:14
  ✖  1:14  path should be listed in the project's dependencies. Run npm i -S path to add it  import/no-extraneous-dependencies

  1 error
```

[ `import/no-extraneous-dependencies` ](import/no-extraneous-dependencies)should ideally be passing such lines.

I have created a test project to show this error: https://github.com/saneef/debug-xo-import-no-extraneous-dependencies

**Comment by sindresorhus** [comment]
Issues with plugins should be opened on the relevant plugins, in this case: https://github.com/benmosher/eslint-plugin-import

XO is just using the default settings: https://github.com/xojs/xo/blob/ca214923a38a3272161f182d3072c30e46766b3a/config/plugins.js#L212

**Comment by privatenumber** [comment]
Based on the answer [here](https://github.com/benmosher/eslint-plugin-import/issues/1396#issuecomment-511007063), xo's `gatherImportResolvers` should add an empty `node: {}` if the env is `node` when automatically setting a Webpack resolver unless otherwise specified by the user.
