### ISSUE TITLE
Enhancement: Shareable Prettier config

### ISSUE THREAD

**Issue by pizzafox** [xojs/xo#484]
[Prettier has support for shareable configs](https://prettier.io/docs/en/configuration.html#sharing-configurations). Should XO have a (published) one?

The XO style in a Prettier v2 config is

```json
{
  "arrowParens": "avoid",
  "bracketSpacing": false,
  "jsxSingleQuote": true,
  "singleQuote": true,
  "trailingComma": "none",
  "useTabs": true
}
```

**Comment by sindresorhus** [comment]
XO already handles setting this config internally, so I shareable config is not really useful for XO itself, and I don't personally use Prettier, so a shareable Prettier config would not be useful to me either. Feel free to publish one if you think it's useful though.

**Comment by pizzafox** [comment]
[prettier-config-xo](https://github.com/pizzafox/prettier-config-xo)
