### ISSUE TITLE
Error: Failed to load plugin 'ava' declared in BaseConfig

### ISSUE THREAD

**Issue by umaar** [xojs/xo#492]
Hey, not seen any issue like this before. Any ideas?

```
Error: Failed to load plugin 'ava' declared in 'BaseConfig » /code/node_modules/xo/config/plugins.js': Cannot find module 'lodash/fp'
Require stack:
- /code/node_modules/enhance-visitors/index.js
- /code/node_modules/eslint-plugin-ava/rules/assertion-arguments.js
- /code/node_modules/import-modules/index.js
- /code/node_modules/eslint-plugin-ava/index.js
- /code/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /code/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /code/node_modules/eslint/lib/cli-engine/cli-engine.js
- /code/node_modules/eslint/lib/cli-engine/index.js
- /code/node_modules/eslint/lib/api.js
- /code/node_modules/xo/index.js
- /code/node_modules/xo/cli-main.js
- /code/node_modules/xo/cli.js
Referenced from: /code/node_modules/xo/config/plugins.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/code/node_modules/enhance-visitors/index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

Node: `v14.4.0`
XO: `0.32.1`
NPM: `6.14.5`
My package.json also includes: `"type": "module"`

**Comment by timbeadle** [comment]
I've just seen this after upgrading to lodash@4.17.17

**Comment by yoursunny** [comment]
I have a CI build that uses `xo`. It succeeded 3 hours ago and failed now.
I looked through all the dependencies of `xo` and `xo-config-ava`. The only dependency updated in the last 3 hours is `lodash`.
Therefore, this is most likely https://github.com/lodash/lodash/issues/4846

**Comment by yoursunny** [comment]
lodash 4.17.17 isn't working either.
https://github.com/lodash/lodash/issues/4848

**Comment by Bauke** [comment]
If you're using Yarn you can get it working by specifying 4.17.15 as a resolution:

```
"resolutions": {
  "lodash": "4.17.15"
}
```

Don't know if there's an npm equivalent.

**Comment by notlmn** [comment]
From https://github.com/lodash/lodash/issues/4837#issuecomment-655609600, this should be fixed after doing a `rm -rf node_modules/ && npm install`, to pull in new `lodash@4.17.18` or up.

CI builds should run fine now unless you have `lodash@4.17.17` pinned somewhere in your dependencies.

**Comment by umaar** [comment]
Thanks! It's working now

**Comment by sinedied** [comment]
I'm running into this issue, using latest xo (0.37.1) and lodash (4.17.20) version.
Tried `rm -rf node_modules/ && npm install`, but no luck :/
