### ISSUE TITLE
XO --fix on pre-commit hook without blocking commit

### ISSUE THREAD

**Issue by daartv** [xojs/xo#494]
Hello!

My issue is the following:
I have sucessfully added `xo --fix` to my pre-commit hooks and it's fixing all autofixable issues, but erroring out with non-autofixable ones, we're in the middle of integrating it so it's a gradual rollout, is there a way to run XO in silent mode so that it shows the error but doesn't block the commit?

I'm using Husky and lint-staged to run the hook.

**Comment by sindresorhus** [comment]
You can probably do it with Bash: `xo --fix || true`. Not sure how to do that cross-platform though. It's not something I intend to support built-in.

**Comment by papb** [comment]
By the way, I can confirm that the `foobar || true` syntax works fine on windows, so that's probably cross-platform, unless it doesn't work on Mac :sweat_smile:

**Comment by daartv** [comment]
Doesn’t seem to work for me on Mac 😅

**Comment by devinrhode2** [comment]
You may need to pass the `--shell "/bin/zsh"` to lint-staged!

**Comment by lkraav** [comment]
Nice idea. https://stackoverflow.com/a/24538676/35946 is an elegant IIFE-ish shell solution, too.
