### ISSUE TITLE
Behaviour of `xo --stdin` and options defined in `package.json`

### ISSUE THREAD

**Issue by dersimn** [xojs/xo#509]
Is this the intended behaviour, that when using `--stdin` just a part of the current `package.json` is parsed and other parts are ignored? Im running the commands from a Terminal where 2 Files exist:

`package.json`:

```json
{
  "devDependencies": {
    "xo": "^0.36.1"
  },
  "xo": {
    "space": 4,
    "globals": [
      "myGlobalFunction"
    ]
  }
}

```

`index.js`:

```javascript
function something(foo) {
    myGlobalFunction(foo);
}

something();

```

1) `npx xo`
    - Runs without errors
2) `cat index.js | npx xo --stdin`: 
    - Returns: `✖  2:5  myGlobalFunction is not defined.  no-undef`
    - However the `space: 4` option is respected.
    - `cat index.js | npx xo --globals myGlobalFunction --stdin` works
    - Maybe because `rules` are simply forwarded to eslint and all other options are parsed by XO ?

Plugins like xojs/SublimeLinter-contrib-xo#17 are facing similar issues because of that.

**Comment by dersimn** [comment]
Reproduce with: https://github.com/dersimn/issue-xo

**Comment by charlesbjohnson** [comment]
I'm running into this as well via https://github.com/dense-analysis/ale/blob/master/ale_linters/javascript/xo.vim. 

The issue seems to have cropped up between https://github.com/xojs/xo/compare/v0.34.2...v0.35.0 so I assume that the root cause can be found within one of the dependencies that was updated and not `xo` itself.

**Comment by dersimn** [comment]
@charlesbjohnson Thanks for the hint. The issue seems to be the update from `"meow": "^7.1.1"` to `"meow": "^8.0.0"`.  

To verify place `console.log('foo', options);` before [line 61 in index.js](https://github.com/xojs/xo/blob/33b769ec71498f4c788fe01e17c043908ad0205d/index.js#L61):

With xo `v0.34.2` (using meow `v7.1.1`) this debug line outputs:
```
foo { stdin: true }
```

With xo `v0.35.0` (using meow `v8.0.0`) this debug line outputs:
```
foo {
  stdin: true,
  env: [],
  global: [],
  ignore: [],
  plugin: [],
  extend: [],
  extension: []
}
```

So probably the behaviour of meow's `isMultiple ` (used for e.g. [here](https://github.com/xojs/xo/blob/33b769ec71498f4c788fe01e17c043908ad0205d/cli-main.js#L64)) changed.
