### ISSUE TITLE
`xo` is slow on `eslint-plugin-unicorn` project

### ISSUE THREAD

**Issue by fisker** [xojs/xo#510]
I've locate problems, it's because

https://github.com/xojs/xo/blob/0ec4b8c0ed58209e8de041d42e60c46163cc3806/index.js#L100-L105

searching `xo` config files, and `eslint-plugin-unicorn` has many files in `test/integration/fixtures` dir, and we can't set config search ignore dirs.

Questions:

1. Why are we searching config files inside dirs? Shouldn't config file in `cwd` or above?
2. Why don't we use `cosmiconfig.search`? Because it don't know how to `mergeOptions`?

**Comment by sindresorhus** [comment]
> Why are we searching config files inside dirs? Shouldn't config file in cwd or above?

I'm honestly not sure. It was added in: https://github.com/xojs/xo/commit/0d63c64da288661bee82155c58a2b058fa0a26ab Maybe there's some clue in there...

> Why don't we use cosmiconfig.search? Because it don't know how to mergeOptions?

I don't have an answer for this either.

---

Maybe @pvdlg would be able to chime in.

**Comment by fisker** [comment]
The config searching logic also effect glob matching, if there is a `xo.config.js` file in subdir, `xo` won't format files outside that dir.

Run

```console
node cli lib/*.js
```

on this project root dir, it won't match any file, because there are many config files in `test/fixtures`

**Comment by fisker** [comment]
I think we can close this now, it's much faster after #583, https://github.com/xojs/xo/issues/510#issuecomment-883020358 also fixed by #583
