### ISSUE TITLE
'@typescript-eslint/quotes' conflict with 'quotes'

### ISSUE THREAD

**Issue by FunctionDJ** [xojs/xo#518]
When using
```json
"xo": {
  "rules": {
    "quotes": [ "error", "double" ]
  }
}
```
then XO will still report double quotes as errors in .ts/.tsx files due to the `@typescript-eslint/quotes` rule.

Overriding the rule the normal way works for those files:
```json
"xo": {
  "rules": {
    "quotes": [ "error", "double" ],
    "@typescript-eslint/quotes": [ "error", "double" ]
  }
}
```
however it will create the following error when analysing .js files:
```
  webpack\react.webpack.js:1:1
  ×   1:1  Definition for rule @typescript-eslint/quotes was not found.  @typescript-eslint/quotes
```

Trying a config like this to only override the rule for .ts/.tsx files doesn't seem to work and takes me back to square one:
```json
"xo": {
  "rules": {
    "quotes": [ "error", "double" ]
  },
  "overrides": [
    {
      "files": [ "*.ts", "*.tsx" ],
      "rules": {
        "@typescript-eslint/quotes": [ "error", "double" ]
      }
    }
  ]
}
```

**Comment by FunctionDJ** [comment]
This is not #501 !

**Comment by FunctionDJ** [comment]
I think this was my issue because i used `*.ts` / `*.tsx` and not `**/*.ts` / `**/*.tsx` in the override. It works now. Sorry!

**Comment by pvinis** [comment]
so is this the way? we need to have the `overrides` part for these?
