### ISSUE TITLE
Parsing error: No Babel config file detected

### ISSUE THREAD

**Issue by groenroos** [xojs/xo#524]
I'm probably missing something obvious... I've been using xo with `babel-eslint` as the `parser` (as suggested in xo's readme) with great success, but today yarn told me that `babel-eslint` has been deprecated and `@babel/eslint-parser` is offered as a direct alternative.

However, swapping xo's `parser` out to `@babel/eslint-parser` makes it angery:

    Parsing error: No Babel config file detected for [file].js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.

I've variously attempted to either set `requireConfigFile` to `false` or to create some sort of Babel config, in an `.eslintrc.js`, in a `babel.config.json`, and in a `"babel"` in `package.json`, all to no effect.

Is there a way to use xo with `@babel/eslint-parser`?

```json
{
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/eslint-parser": "^7.13.4",
    "xo": "^0.38.2"
  },
  "xo": {
    "parser": "@babel/eslint-parser"
  }
}
```

    % node -v
    v14.16.0
    % npm -v
    6.14.11

**Comment by XhmikosR** [comment]
```diff
  "xo": {
+    "parser": "@babel/eslint-parser",
+    "parserOptions": {
+      "requireConfigFile": false
+    }
    }
```
