### ISSUE TITLE
Default to ESM

### ISSUE THREAD

**Issue by sindresorhus** [xojs/xo#530]
I plan to make XO default to ESM this year. That means banning CommonJS syntaxes and conventions. I'll add an opt-out like `esm: false`, but it will be `true` by default.

For example, we'll enable this rule: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1141

**Comment by sindresorhus** [comment]
I decided not to do an opt-out. It's not something I personally need or something I want to encourage, and it's a lot of work that will only be needed for a short amount of transitionary time. If you cannot move to ESM just yet, I recommend just staying on XO 0.39.

**Comment by fregante** [comment]
The opt out still exists but it's manual, I think. I have a CJS webpack config where I just had to disable 2/3 rules related to imports and requires

**Comment by dartess** [comment]
@sindresorhus projects for Node often remain CJS. I can understand the reasons for abandoning this format. But freezing the version causes new problems. Right now we're having problems with the audit:

```
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install xo@0.48.0, which is a breaking change
node_modules/globby/node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/globby/node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/globby
      xo  0.20.0 - 0.41.0
      Depends on vulnerable versions of globby
      node_modules/xo
```

Is it possible to release version `0.39.2` with dependency update?
