### ISSUE TITLE
xo is using an older version of type-fest that does not have `Expect` type mentioned in eslint-config-xo-typescript `ban-type` rule

### ISSUE THREAD

**Issue by darcyparker** [xojs/xo#535]
xo is using an older version of type-fest that does not have [`Expect` type mentioned in this ban-type rule](https://github.com/xojs/eslint-config-xo-typescript/blob/a9481df0e9b382287ce94fd3ec394bf9d59dae51/index.js#L87) in eslint-config-xo-typescript.

`Expect` is the correct type name to recommend because `Omit` was renamed to `Expect` in https://github.com/sindresorhus/type-fest/pull/44.

But the version of type-fest installed with `npm install xo` is `0.21.3`. (A version before `Omit` was renamed to `Expect`... )
=> So out of the box, `xo` is recommending a type that does not exist.

As a workaround, I tried `npm install type-fest@latest`, but this installs `^1.0.2`, for which there is no `Omit` or `Expect`...
* It appears these types were removed from type-fest?
* So  maybe the recommendation/rule in eslint-config-xo-typescript should be removed?
* Or maybe a peer-dependency should be added to xo with an applicable version of type-fest that has `Expect`?

I am not sure what the right solution is.  It's just a problem that xo is recommending a type that does not exist with a simple `npm install xo`.

**Comment by sindresorhus** [comment]
XO doesn't directly depend on `type-fest`. There's no `type-fest` dependency in package.json.

**Comment by darcyparker** [comment]
Yes - you're right.  My mistake for opening issue here.

**Comment by darcyparker** [comment]
I also realized I can't spell... I was typing `Expect` instead of `Except`...
