### ISSUE TITLE
Support for YAML config

### ISSUE THREAD

**Issue by fregante** [xojs/xo#536]
These are the names/types of config allowed: https://github.com/xojs/xo/blob/fd8828dd58e64e9b9b8779670698340d37e71725/lib/constants.js#L118-L124

But both eslint and cosmiconfig natively support YAML files as config:

- https://github.com/davidtheclark/cosmiconfig
- https://eslint.org/docs/user-guide/configuring/configuration-files#using-configuration-files

So it'd be great to see support here too, enabling comments without having to deal with JS files (e.g. https://github.com/xojs/xo/issues/468)

**Comment by sindresorhus** [comment]
That was an intentional choice. YAML is an awful format. I don't want to encourage use of it. I'd rather support JSON with comments if that's truly needed, but I think it's better to just use JS for config then.

**Comment by fregante** [comment]
> I think it's better to just use JS for config then.

I suppose that could work, hoping that https://github.com/xojs/xo/issues/468 is fixed soon. It was the reason why RG changed the config to JSON in https://github.com/sindresorhus/refined-github/pull/4002

ESLint also seems to have the same issue with config in ESM packages: https://github.com/eslint/eslint/issues/14137

---

I suppose https://github.com/xojs/xo/issues/428 would also be a solution to this issue 😁
