### ISSUE TITLE
Add rule `consistent-type-imports` from `typescript-eslint`

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#539]
[Rule docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

Now that `import/order` has been re-enabled maybe some TypeScript-specific import rules should be added.

I personally prefer having [`prefer` set to `type-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md#prefer), which requires types imported during build-time to be done with `import type Foo from '...'`. Using this option is also a workaround for a bug in `import/no-cycle` that thinks `import Foo from '...'` is importing a value and not a type.

**Comment by sindresorhus** [comment]
I'm not sure about forcing type-imports. According to the TypeScript maintainers, you should rarely need them: https://twitter.com/drosenwasser/status/1218253620077981696

**Comment by fregante** [comment]
I used to agree with that, but I've liked them because:

- it makes type-only imports explicit
- it ensures that you're actually importing only a type and nothing else

```ts
import {Config} from 'eslint'
```

could lead to vastly different results from:


```ts
import type {Config} from 'eslint'
```

… which is very explicit on what it does.

**Comment by sindresorhus** [comment]
I agree. I use type imports a lot now too.
