### ISSUE TITLE
Don't agree with 2 new rules

### ISSUE THREAD

**Issue by jimmywarting** [xojs/xo#548]
[Got 2 new kind of errors](https://github.com/node-fetch/fetch-blob/pull/93/checks?check_run_id=2563521477) i don't like

Error: /home/runner/work/fetch-blob/fetch-blob/test.js: line 102, col 32, Error - Prefer the spread operator over `Array#slice()`. (unicorn/prefer-spread)
Error: /home/runner/work/fetch-blob/fetch-blob/test.js: line 230, col 29, Error - Invalid group length in numeric value. (unicorn/numeric-separators-style)

> Prefer the spread operator over `Array#slice()`. (unicorn/prefer-spread)

You are not suppose to spread `Blob`s with `chunk = blob.slice(start, end)` You need to make sure that what is sliced is actually an array

`numeric-separators-style` I just don't agree with this... 

Personally I want a linter do just spot error and stuff that are deprecated.
i hate rules that change the coding style just b/c one person decided it should be formated in one flavor over the other. 
If it works perfectly fine to do something in one other way over another then it should not throw an error
I don't want to have rules like tab vs space or `;` vs no `;`

- I may want to break the numeric-separators-style just b/c i target a older environment and dosen't use any compiler
- I don't think separator style don't enhance much readability, i think they looks more like a key/serial number for a code activation when it in fact is a number
- I may want to use x over y because of performances reasons

the `node:` prefix was good doe

**Comment by sindresorhus** [comment]
> You need to make sure that what is sliced is actually an array

There's no way to statically know that it's actually a `Blob`. We assume most cases are arrays, and you can use ESLint ignore comments for the rest. That's just how JS listing works. TypeScript has much better ability to detect types. We could maybe in this specific case disable it if the variable name is `blob`, but that's the best we could do.

> numeric-separators-style I just don't agree with this...

There will always be rules people disagree with. XO is very opinionated towards strict and readable code. Numeric separators were introduced exactly to improve readability of large numbers.

**Comment by slaweet** [comment]
I'm also not a fan `numeric-separators-style` rule. I see that XO is fulfilling its proposition to be an opinionated tool, so I'll just share an example of what issues is the rule causing out there. 

The maintainer of https://github.com/Qix-/color formatted the `color` NPM package using XO, now some people using the package need extra transpilation setup (as described in https://github.com/Qix-/color/issues/206 and https://github.com/Qix-/color/issues/204)
