### ISSUE TITLE
Allow to configure curly spacing like Prettier

### ISSUE THREAD

**Issue by BasixKOR** [xojs/xo#549]
For now, the only way to turn on curly spacing is using Prettier with `bracketSpacing`, or just override the rules directly.

I prefer curly spacing personally, and I think it should be configurable easily as Prettier does.

**Comment by sindresorhus** [comment]
Thanks for the suggestion. I'm unfortunately not going to add this. XO has existed for years and this is the first time this is being requested, so it doesn't seem like a common need. I'm also the only one maintaining XO and I don't really want more complexity to maintain.

**Comment by papb** [comment]
I also prefer curly spacing, but I just overwrite the rule in package.json, and it has always worked. [Example](https://github.com/papb/json-excel/blob/454354f246889e0da9924a8673c1403989d119f8/package.json#L87-L90)
