### ISSUE TITLE
Recent release broke vscode extension

### ISSUE THREAD

**Issue by Spence-S** [xojs/xo#563]
XO is a great project. I love it and do not want to abandon. But I'm sad that recent releases prevent me from upgrading to XO latest because it just doesn't work with the vscode extension. 

I'm only opening this here to get more visibility because I expect this will be a big problem for a huge number of users, and the xo community in general, in the near future, as they upgrade or start new projects. 

Hopefully we can get the extension some love or revert the incompatible change.

Here is the extension issue:
https://github.com/SamVerschueren/vscode-linter-xo/issues/91

Error is:
> Failed to load XO library. Make sure XO is installed in your workspace folder using 'npm install xo' and then press Retry.

Note: the cli still works as expected

**Comment by Spence-S** [comment]
I forked and published this package as a new extension - since it seems the original extension is no longer being maintained or accepting PRs. Please try this via the link below, and feel free to file issues in my fork. My extension should work now for all versions of XO!

https://marketplace.visualstudio.com/items?itemName=spence-s.linter-xo

**Comment by fregante** [comment]
I think this has been fixed. I've been using XO in VSCode since then
