### ISSUE TITLE
Require extension/be explicit 

### ISSUE THREAD

**Issue by jimmywarting** [xojs/xo#592]
Code: `import x from './index.js'`

```
  ✖  2:1   Do not reference the index file directly                unicorn/import-index
  ✖  2:28  Unexpected use of file extension "js" for "./index.js"  import/extensions
```

Ryan dhal regret the hole extension less import.
Extension-less do not work in Deno or Browser. Using extension less paths is a footgun

**Comment by sindresorhus** [comment]
XO already enforces extension. I'm not sure what you're requesting?

**Comment by jimmywarting** [comment]
you were right, just had a old version installed
