### ISSUE TITLE
Support `--report-unused-disable-directives` in ESLint 8

### ISSUE THREAD

**Issue by fregante** [xojs/xo#594]
https://twitter.com/joshuakgoldberg/status/1426704205088280588?s=21

**Comment by fregante** [comment]
It looks like this is an old flag actually. V8 only added support for autofixing. 

https://github.com/eslint/eslint/issues/9382

**Comment by sindresorhus** [comment]
See https://github.com/xojs/xo/pull/359

**Comment by fregante** [comment]
Indeed, I didn't remember if it also worked on full-file `eslint-disable` directives. If so I suppose it can be closed.

**Comment by sindresorhus** [comment]
We can keep it open until we can confirm it works well.

**Comment by fregante** [comment]
It works

![text](https://user-images.githubusercontent.com/1402241/183241205-73b082d9-6d25-4870-8ee3-10bda012e81f.gif)

Side note: XO is too slow. 6s to scan a folder with a single 300-lines file is not reasonable 😔
