### ISSUE TITLE
Env is set to CommonJS and Unicorn's prefer-module error keeps getting thrown

### ISSUE THREAD

**Issue by TropicalRaisel** [xojs/xo#596]
The error description is [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/prefer-module.md#prefer-javascript-modules-esm-over-commonjs).

I'd assume that xo would cover disabling this rule in when the commonjs env is set.

**Comment by sindresorhus** [comment]
XO requires your project to be ESM. CommonJS is no longer supported.

https://github.com/xojs/xo/releases/tag/v0.40.0
