### ISSUE TITLE
Redundant `for ... of` rules for TypeScript files

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#603]
`@typescript-eslint/prefer-for-of` and `unicorn/no-for-loop` seem to both do the same thing.

**Comment by sindresorhus** [comment]
This would be more actionable if you did a more in-depth comparison. For example, `unicorn/no-for-loop` might catch some cases that `@typescript-eslint/prefer-for-of` do not.

**Comment by fregante** [comment]
One example:

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1836
