### ISSUE TITLE
Variable naming rule(s)

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#608]
The [`@typescript-eslint/naming-convention`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#readme) rule has many possible configurations to enforce variable naming conventions. If possible it should be used to ensure consistent naming style in a project, especially for constants (defined below) being named with `UPPER_SNAKE_CASE`.

1. Constants are entirely readonly and never modified
2. Constants are declared at the highest level scope (ex. not declared in a function)

Related:
- #463

**Comment by sindresorhus** [comment]
https://github.com/xojs/eslint-config-xo-typescript/blob/e09d7ce13cec8d3684bb03345212dfe54b910631/index.js#L277-L281

**Comment by jonahsnider** [comment]
Do those bugs prevent any progress from being made on this? It seems like name validation for constants could be added while we wait for better class support.

**Comment by flying-sheep** [comment]
How to best circumvent the false positives while keeping the rest? Basically I want to apply this diff to my config:

```diff
 '@typescript-eslint/naming-convention': [
   'error', {
     selector: 'default',
     format: [
       'strictCamelCase'
+      'strictPascalCase'
     ],
```
