### ISSUE TITLE
Disable ava

### ISSUE THREAD

**Issue by devinrhode2** [xojs/xo#610]
I think ava is great, but I am working on a purely frontend project, so have no need for it.

I think for now I can just use `patch-package`, I'm not sure of a good design to "remove" or "disable" a plugin.

Maybe, it would make sense to group it along with `vue` and `react` - not included by default

**Comment by sindresorhus** [comment]
The AVA rules only apply to AVA test files, so I don't really see the problem. Are you encountering any error?

**Comment by devinrhode2** [comment]
Not encountering any errors, just being picky 😊

One benefit would be faster npm installs.

How does XO detect ava test files? *.test.*? Perhaps if that detection is not trivial, there would also be performance boost here

(although - ava looks _super_ nice)

Closing as it's not a real "issue" - but, we can keep discussing

**Comment by sindresorhus** [comment]
> One benefit would be faster npm installs.

That would be negligible.

> How does XO detect ava test files?

It just checks the import statement. I don't think that has much overhead.
