### ISSUE TITLE
XO v0.45.1?

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#612]
https://github.com/xojs/eslint-config-xo-typescript/releases/tag/v0.45.1 was released to fix a bug but XO itself never received an update.
Will XO receive a v0.45.1 update with the upstream bug fix?

It's currently blocking me from upgrading to the latest XO, although as a workaround users could use a custom version resolution for `eslint-config-xo-typescript`.

**Comment by sindresorhus** [comment]
Semver handles this for us. Read more here: https://nodesource.com/blog/semver-tilde-and-caret

Just reinstall XO and you'll get the latest `xojs/eslint-config-xo-typescript`.
