### ISSUE TITLE
 "Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context." in update to 0.45.0

### ISSUE THREAD

**Issue by muziejus** [xojs/xo#615]
Upgrading from 0.44.0 to 0.45.0 has caused xo to fail giving this error. I've found documentation about it for eslint, but that documentation is all very old, and I still get the error with setting my eslint parseroptions like this:

```js
  parserOptions: {
    ecmaVersion: 12,
    sourceType: "module",
    ecmaFeatures: {
      legacyDecorators: true,
    },
  },
```

The parser in the .xo-config.json is set to `babel-eslint`, which is at 10.1.0. This is in an ember project, using node 14.18.0.

Running eslint and prettier work fine, outside of complaining about not understanding some rules.

**Comment by bishwambharsen** [comment]
Thanks @muziejus your solution really helped me. :)

**Comment by RainyCityCoder** [comment]
@sindresorhus
@muziejus 

Your posts were helpful! Thank you!
