### ISSUE TITLE
Upgrade to ESLint 8

### ISSUE THREAD

**Issue by sindresorhus** [xojs/xo#618]
https://eslint.org/blog/2021/10/eslint-v8.0.0-released

Blocked by:
- [x] https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1488
- [x] https://github.com/avajs/eslint-plugin-ava/issues/335
- [x] https://github.com/typescript-eslint/typescript-eslint/issues/3738
- [x] https://github.com/import-js/eslint-plugin-import/issues/2211

**Comment by fregante** [comment]
Will you also change how dependencies are handled as part of this issue? That is, "don't depend on `eslint-plugin-ava` directly, but through `eslint-config-xo`"
