### ISSUE TITLE
Where does XO include eslint-comfig-xo?

### ISSUE THREAD

**Issue by devinrhode2** [xojs/xo#634]
I was looking at this eslint config file, but I'm confused as to why it doesn't actually extend the xo config.

https://github.com/xojs/xo/blob/main/config/plugins.cjs#L26

Also, maybe there shouldn't be any rules in this file. Shouldn't they be inside of eslint-comfig-xo?

Lastly with the repeated ~5 lines at the very top, couldn't we include XO via a classic lodash extends/deep merge call?

**Comment by fisker** [comment]
https://github.com/xojs/xo/blob/1d2409f4fe9bb35eeee968bd80dbe7e843d14d45/lib/options-manager.js#L54
