### ISSUE TITLE
Consider using `@rushstack/no-new-null` for TypeScript

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#645]
`@rushstack/eslint-plugin` exposes a [`@rushstack/no-new-null`](https://github.com/microsoft/rushstack/tree/master/eslint/eslint-plugin#rushstackno-new-null) rule which may do a better job limiting the use of `null` in TypeScript than the current behavior.

**Comment by sindresorhus** [comment]
How does it do a better job?

**Comment by jonahsnider** [comment]
Their plugin will only error when `null` is used in a public interface. For example, if you were writing a class that used an external API, then having a private method which used `null` to describe an external JSON API would be allowed.

**Comment by sindresorhus** [comment]
I don't want to allow `null` in internal contexts either. I think it's better to just use ignore comments when you absolutely have to use `null`.
