### ISSUE TITLE
Better solution for configs & plugins in dependencies

### ISSUE THREAD

**Issue by jonahsnider** [xojs/xo#646]
It's been nearly 6.5 years since eslint/eslint#3458 was opened and very little progress has been made on their side.
What can we do to improve the XO user experience while we wait for a fix from ESLint?

The best solution seems to be using Microsoft's  [@rushstack/eslint-patch](https://github.com/microsoft/rushstack/tree/master/eslint/eslint-patch) to patch ESLint's module resolver.

Another solution which worked for TypeScript + XO users is using `bundledDependencies` in `package.json`.

Related:
- #466
- #473
- #483
- #441 ?
- #642 ?

Most issues are for XO + Prettier.

**Comment by sindresorhus** [comment]
> It's been nearly 6.5 years since eslint/eslint#3458 was opened and very little progress has been made on their side.

I wouldn't say that. They're working on a new config format which will enable this: https://github.com/eslint/eslint/issues/13481 It's likely it will happen this year: https://github.com/eslint/eslint/issues/15383#issuecomment-985039801

**Comment by sindresorhus** [comment]
> The best solution seems to be using Microsoft's @rushstack/eslint-patch to patch ESLint's module resolver.

This patches ESLint and could break at any time. It might also break certain cases. I don't think I want to risk that.

> Another solution which worked for TypeScript + XO users is using bundledDependencies in package.json.

I'm unlikely to bundle dependencies in XO.

**Comment by jonahsnider** [comment]
> This patches ESLint and could break at any time. It might also break certain cases. I don't think I want to risk that.

Could enabling the patch be done via a CLI flag so it's explicitly opt-in?

**Comment by sindresorhus** [comment]
It technically could, but I'm still the one that has to deal with any issues that occur with the CLI flag specified. I would personally prefer to just wait it out.

**Comment by mmkal** [comment]
I wrote a [wrapper plugin](https://www.npmjs.com/package/eslint-plugin-wrapper) that requires no patching, plays by the rules of eslint and nodejs, and allows plugins and configs to act pretty much like normal dependencies. As a bonus, it lets you locally define rules for your project that don’t need to be published in a separate package. It’s also pretty simple, just a single file with no dependencies itself. (There is a trade off - it prefixes the rules it wraps, and requires using a JavaScript, not json/yaml, config file)

We’ve been using it at my work for a while and it works well enough, while we wait for the proper solution.

**Comment by fregante** [comment]
The flat config has landed. This is the way to go now:

- https://github.com/xojs/xo/issues/702
