### ISSUE TITLE
npm package bundles node_modules?

### ISSUE THREAD

**Issue by jablko** [xojs/xo#651]
I noticed that some versions' npm package bundles a node_modules directory, e.g.
- https://unpkg.com/browse/xo@0.46.1/node_modules/
- https://unpkg.com/browse/xo@0.46.3/node_modules/
- https://unpkg.com/browse/xo@0.46.4/node_modules/
- https://unpkg.com/browse/xo@0.47.0/node_modules/
- https://unpkg.com/browse/xo@0.48.0/node_modules/

Versions without node_modules are [+/- 11 files and +/- 64 kB](https://www.npmjs.com/package/xo/v/0.46.2) vs. versions with are [+/- 1,800 files and +/- 6 MB](https://www.npmjs.com/package/xo/v/0.48.0).

I'm also getting an error installing an XO dependant with npm 7:
```sh
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/runner/work/remark-lint/remark-lint/node_modules/xo/node_modules/typescript/bin/tsc'
```

Don't know for sure if the bundled node_modules is the culprit, but it looked unintended. Is it?

I haven't figured out why it's there in some versions and not others. I'd assumed that `npm publish` would [exclude node_modules](https://docs.npmjs.com/cli/v8/commands/npm-publish#files-included-in-package). It *is* listed in .gitignore ...

**Comment by sindresorhus** [comment]
More context here: https://github.com/xojs/xo/pull/624 In short, it's needed to work around npm bugs.

**Comment by jablko** [comment]
Gotcha:
- npm >= 8 (Node.js >= 16) works
- npm <= 6 (Node.js <= 14) without `bundledDependencies`: `@typescript-eslint/parser` is hoisted, `typescript` isn't -> `Cannot find module 'typescript'` 100% of the time
- npm 7 with `bundledDependencies`: `npm ERR! enoent ENOENT: no such file or directory, chmod '/home/runner/work/remark-lint/remark-lint/node_modules/xo/node_modules/typescript/bin/tsc'`
  - Caused by `bundledDependencies`? Smells like it but unconfirmed.
  - Under what conditions?
    - If you install `xo`, `typescript@4.5.5` -> `node_modules/typescript` and succeeds.
    - If you install `remark-lint`, `typescript@4.4.4` -> `node_modules/typescript`, presumably `typescript@4.5.5` -> `node_modules/xo/node_modules/typescript`? and fails.
    - `xo` [doesn't bundle `typescript`](https://unpkg.com/browse/xo@0.47.0/node_modules/)
    - `node_modules/xo/node_modules/typescript/bin/tsc` [should exist](https://unpkg.com/browse/typescript@4.5.5/bin/tsc)?

I tried summarizing on the npm issue tracker: https://github.com/npm/cli/issues/4441

Thanks!
