### ISSUE TITLE
Use tsconfig/bases/strictest

### ISSUE THREAD

**Issue by devinrhode2** [xojs/xo#662]
If we wanted to be maximally opinionated, use: https://github.com/tsconfig/bases/blob/main/bases/node16-strictest-esm.combined.json

I personally do not like unit testing (yet), so XO with the "strictest" base tsconfig I think would be amazing!

If we wanted to be slightly less opinionated, we can just use the "strictest" config here: https://github.com/tsconfig/bases/blob/main/bases/strictest.json

**Comment by sindresorhus** [comment]
I believe we already have the strictest config: https://github.com/xojs/xo/blob/f952701372b162e539d1752d173a6c730eb08a33/lib/constants.js#L121-L131

Not all compiler properties apply to the TS ESlint plugin.

**Comment by devinrhode2** [comment]
Interesting. How can XO know what compiler settings have any effect on the TS ESLint plugin? The project could export an object type 💡

This gets me thinking,
What if instead of having ANY defaults here, we just fail and tell the user to add their own tsconfig
