### ISSUE TITLE
0.52 extending tsconfig from node_modules causes error

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/xo#679]
I assume this is from #677 

```plaintext
Error: ENOENT: no such file or directory, open '<path>/<project-working-directory>/<extends-string>'
```

The extends string seems to be exactly what is specified in the `tsconfig.json` `extends` value.

I tried both `@sindresorhus/tsconfig` and `@sindresorhus/tsconfig/tsconfig.json` and both fail.
This happens both locally on macOS and Linux and in GitHub CI Runners.

**Comment by sindresorhus** [comment]
// @Spence-S

**Comment by Spence-S** [comment]
@EdJoPaTo thanks for the report, will get this fixed ASAP. Overlooked that extends uses node resolution and not always relative paths to extend from.

**Comment by sindresorhus** [comment]
https://github.com/xojs/xo/releases/tag/v0.52.1
