### ISSUE TITLE
Re-enable `eslint-plugin-promise` as it now supports ESLint 8

### ISSUE THREAD

**Issue by qyurila** [xojs/xo#699]
Currently the config file has [`eslint-plugin-promise`](https://github.com/eslint-community/eslint-plugin-promise) plugin and rules  [commented-out](https://github.com/xojs/xo/blob/main/config/plugins.cjs#L18). The comment says it's disabled as the plugin doesn't support ESLint 8 yet.

Since `eslint-plugin-promise` 6.0.0 [introduced ESLint 8 support](https://github.com/eslint-community/eslint-plugin-promise/blob/HEAD/CHANGELOG.md#600), I think it can be re-enabled now.

**Comment by fregante** [comment]
Note that this plugin is now part of the `eslint-community` group so it might get more attention and support as a consequence.
