### ISSUE TITLE
EACCESS: permission denied on ignored directory

### ISSUE THREAD

**Issue by nicolas-goudry** [xojs/xo#737]
I have the following issue trying to run xo on my project :

```
> xo-eaccess-permission-denied-on-ignored-dir@1.0.0 lint
> xo

Error: EACCES: permission denied, scandir '/fakepath/xo-eaccess-permission-denied-on-ignored-dir/.data/mysql/#innodb_redo'
```

I created a [repository to reproduce this issue](https://github.com/nicolas-goudry/xo-eaccess-permission-denied-on-ignored-dir).

To better explain, I have a MySQL container running alongside my Node.js API, and I’m mounting its data directory in a `.data` directory at my project root. I added the `.data` to `.gitignore`, expecting xo to actually ignore it, but it still tries to scan the subdirectories of `.data`, as per the error message.

Also tried adding `.data/**/*` to `.gitignore`, as well as adding them to the `ignores` xo config field, with same results.

---

EDIT: I know I can fix this by running something like this: `sudo chgrp -R $(whoami) .data/mysql` but I still think this is a bug.

**Comment by nicolas-goudry** [comment]
I took a look at the code, and the error seems to come from the call to `globby` inside the `globFiles` function, on line 29. I’ll keep digging.

**Comment by nicolas-goudry** [comment]
Looking back at this, I now think I understand what does the `isIgnoredByIgnoreFiles` function: return a list of ignore files relative to the current working directory.

I think this is the issue, because it’s actually trying to search for an ignore file inside the `.data` directory, to which it doesn’t have access permission.

If I update the code of `isIgnoredByIgnoreFiles` to add the `options.ignore` to the `ignoreFilesGlobOptions.ignore`, the issue goes away.

Something like that (dirty):

```js
export const isIgnoredByIgnoreFiles = async (patterns, options) => {
	const {cwd, suppressErrors, deep} = normalizeOptions(options);

	const paths = await fastGlob(patterns, {
		cwd,
		suppressErrors,
		deep,
		...ignoreFilesGlobOptions,
		ignore: [...ignoreFilesGlobOptions.ignore, ...options.ignore],
	});

	const files = await Promise.all(
		paths.map(async filePath => ({
			filePath,
			content: await fs.promises.readFile(filePath, 'utf8'),
		})),
	);

	return getIsIgnoredPredicate(files, cwd);
};
```

Would you like me to open an issue in `globby`’s repository instead ?

**Comment by fregante** [comment]
That issue and PR seem to be closed 🎉
