### ISSUE TITLE
Promise plugin supports ESLint 8 now

### ISSUE THREAD

**Issue by lishaduck** [xojs/xo#754]
https://github.com/xojs/xo/blob/ee9f0a3d72d55df098fc321c4d54a1ea3804e226/config/plugins.cjs#L17-L18

I'll try to PR sometime, but just FYI, @eslint-community is maintaining `eslint-plugin-promise` and @mysticatea's plugins (`eslint-plugin-eslint-comments`)

**Comment by lishaduck** [comment]
Oh, #656 and #699.
I think it's better maintained enough now to be worth considering.

**Comment by fregante** [comment]
Duplicate of https://github.com/xojs/xo/issues/699
