### ISSUE TITLE
TS Strict config not working

### ISSUE THREAD

**Issue by Sufiane** [xojs/xo#755]
I'm playing around with XO, and can't get away from the following error:

```
This rule requires the strictNullChecks compiler option to be turned on to function correctly. @typescript-eslint/prefer-nullish-coalescing
```

It should work out of the box since xo should handles as stated [here](https://github.com/xojs/xo?tab=readme-ov-file#typescript)

I even turned everything on in my own tsconfig.json, but w/o success.

Since I've seen in other issues that restarting your IDE (Webstorm in my case) may work I've done it. No success either.

Did I missed something ?

**Comment by fregante** [comment]
Did you enable `strictNullChecks`? I have no problem using XO with packages based on this tsconfig: https://github.com/sindresorhus/tsconfig

**Comment by fregante** [comment]
Either way, the error comes from `typescript-eslint` and it's related to your config rather than XO.

**Comment by Marpfie** [comment]
I have the same Issue.
In my tsconfig.json I clearly configured strict

```    "strict": true,
    "strictNullChecks": true,```

Yet xo throws an error for every rule
>>>   ✖    0:1    This rule requires the strictNullChecks compiler option to be turned on to function correctly.                                                                                                                                                                                                                                                                                                                                                                                                                       @typescript-eslint/prefer-nullish-coalescing
