### ISSUE TITLE
xo 0.59 with typescript projects fails with n/file-extension-in-import

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/xo#763]
Using `xo` >= 0.59.0 with TypeScript projects is quite useless because of [`n/file-extension-in-import`](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/file-extension-in-import.md):

```plaintext
source/index.ts:1:15
  ✖   1:15  forbid file extension .js.  n/file-extension-in-import
  ✖   2:15  forbid file extension .js.  n/file-extension-in-import
  ✖   4:15  forbid file extension .js.  n/file-extension-in-import
```

It's configured in xo here:

https://github.com/xojs/xo/blob/c96584342b41412883abeab2a63155fbddc30589/config/plugins.cjs#L314-L325

Not sure what's needed to fix this in order to update xo to the current version in TypeScript projects. `xo` 0.58 works perfectly fine.

**Comment by sindresorhus** [comment]
// @melusc

**Comment by melusc** [comment]
Can reproduce in v0.59.0 through v0.59.2, but not in v0.58.0

**Comment by EdJoPaTo** [comment]
Maybe related to #756? @abiriadev

**Comment by abiriadev** [comment]
I will investigate this

**Comment by melusc** [comment]
Starting with this commit <https://github.com/eslint-community/eslint-plugin-n/commit/dc9f4731907a6408b2971e6ee833eba4c5c16adf> that error appears
